package:
  name: prefect-test-noarch-dependency
  version: 1.0
source:
  path: ../src
build:
  noarch: python
  number: 1
about:
  home: https://github.com/AnacondaRecipes/prefect-test-noarch-dependency-feedstock
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
extra:
  recipe-maintainers:
    - dkomisar
